# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/hamas/Documents/Carleton/ELEC3500/Lab9/Microphone - v2/lab9_v2/lab9_v2.srcs/sources_1/ip/cic_compiler_0/cic_compiler_0.xci
# IP: The module: 'cic_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hamas/Documents/Carleton/ELEC3500/Lab9/Microphone - v2/lab9_v2/lab9_v2.srcs/sources_1/ip/cic_compiler_0/cic_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_compiler_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/hamas/Documents/Carleton/ELEC3500/Lab9/Microphone - v2/lab9_v2/lab9_v2.srcs/sources_1/ip/cic_compiler_0/cic_compiler_0.xci
# IP: The module: 'cic_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hamas/Documents/Carleton/ELEC3500/Lab9/Microphone - v2/lab9_v2/lab9_v2.srcs/sources_1/ip/cic_compiler_0/cic_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
